#include "Global.h"

#include "OpenGL.hpp"

OpenGL OpenGL::mInstance;
unsigned int OpenGL::mVertexCount;

PFNGLCLIENTACTIVETEXTUREPROC OpenGL::glClientActiveTexture;
PFNGLACTIVETEXTUREPROC OpenGL::glActiveTexture;

PFNGLGENBUFFERSPROC OpenGL::glGenBuffers;
PFNGLBINDBUFFERPROC OpenGL::glBindBuffer;
PFNGLBUFFERDATAPROC OpenGL::glBufferData;
PFNGLDELETEBUFFERSARBPROC OpenGL::glDeleteBuffers;

PFNGLATTACHSHADERPROC OpenGL::glAttachShader;
PFNGLCOMPILESHADERPROC OpenGL::glCompileShader;
PFNGLCREATEPROGRAMPROC OpenGL::glCreateProgram;
PFNGLCREATESHADERPROC OpenGL::glCreateShader;
PFNGLDELETEPROGRAMPROC OpenGL::glDeleteProgram;
PFNGLDELETESHADERPROC OpenGL::glDeleteShader;
PFNGLLINKPROGRAMPROC OpenGL::glLinkProgram;
PFNGLSHADERSOURCEPROC OpenGL::glShaderSource;
PFNGLUSEPROGRAMPROC OpenGL::glUseProgram;
PFNGLGETUNIFORMLOCATIONPROC OpenGL::glGetUniformLocation;
PFNGLVERTEXATTRIB4FVARBPROC OpenGL::glVertexAttrib4fvARB;
PFNGLGETATTRIBLOCATIONPROC OpenGL::glGetAttribLocation;
PFNGLUNIFORMMATRIX4FVARBPROC OpenGL::glUniformMatrix4fvARB;
PFNGLUNIFORM3FPROC OpenGL::glUniform3f;
PFNGLUNIFORM1IPROC OpenGL::glUniform1i;

PFNGLVERTEXATTRIBPOINTERPROC OpenGL::glVertexAttribPointer;
PFNGLENABLEVERTEXATTRIBARRAYPROC OpenGL::glEnableVertexAttribArray;
PFNGLDISABLEVERTEXATTRIBARRAYPROC OpenGL::glDisableVertexAttribArray;

PFNGLGENPROGRAMSARBPROC OpenGL::glGenProgramsARB;
PFNGLPROGRAMSTRINGARBPROC OpenGL::glProgramStringARB;
PFNGLBINDPROGRAMARBPROC OpenGL::glBindProgramARB;
PFNGLDELETEPROGRAMSARBPROC OpenGL::glDeleteProgramARB;
PFNGLPROGRAMENVPARAMETER4FARBPROC OpenGL::glProgramEnvParameter4fARB;
PFNGLPROGRAMLOCALPARAMETER4FARBPROC OpenGL::glProgramLocalParameter4fARB;

PFNGLBINDFRAMEBUFFEREXTPROC OpenGL::glBindFramebufferEXT;
PFNGLDELETEFRAMEBUFFERSEXTPROC OpenGL::glDeleteFramebuffersEXT;
PFNGLGENFRAMEBUFFERSEXTPROC OpenGL::glGenFramebuffersEXT;
PFNGLBINDRENDERBUFFEREXTPROC OpenGL::glBindRenderbufferEXT;
PFNGLDELETERENDERBUFFERSEXTPROC OpenGL::glDeleteRenderbuffersEXT;
PFNGLGENRENDERBUFFERSEXTPROC OpenGL::glGenRenderbuffersEXT;
PFNGLFRAMEBUFFERRENDERBUFFEREXTPROC OpenGL::glFramebufferRenderbufferEXT;
PFNGLRENDERBUFFERSTORAGEEXTPROC OpenGL::glRenderbufferStorageEXT;
PFNGLFRAMEBUFFERTEXTURE2DEXTPROC OpenGL::glFramebufferTexture2DEXT;
PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC OpenGL::glCheckFramebufferStatusEXT;