#ifndef NETWORK_EVENT_HPP
#define NETWORK_EVENT_HPP

#define NETEVENT_DATA_SIZE 256

enum NetworkEventType {
	NET_DISCONNECT,
	NET_CONNECT_RESULT,
	NET_PAK_NET_STATUS,
	NET_PAK_LOGIN_RESULT,
	NET_PAK_CHANNEL_LIST,
	NET_PAK_SELECT_SERVER,
	NET_PAK_SERVER_JOIN,
	NET_PAK_CHARACTER_LIST,
	NET_PAK_GAME_SERVER_IP,
	NET_PAK_PLAYER_DATA,
	NET_PAK_MOVE_PLAYER,
	NET_PAK_MOVE_NPC,
	NET_PAK_JOIN_ZONE,
	NET_PAK_SPAWN_NPC,
	NET_PAK_SPAWN_MONSTER,
	NET_PAK_SPAWN_AVATAR,
	NET_PAK_DELETE_OBJECT,
	NET_PAK_TELEPORT,
	NET_PAK_LOCAL_CHAT,
	NET_PAK_DAMAGE,
};

struct NetworkEvent {
	virtual ~NetworkEvent(){}

	int _evt_type;
	int srvID;
};

struct NetworkEventData : public NetworkEvent {
	char data[NETEVENT_DATA_SIZE];
};

#endif